import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:icook_mobile/core/constants/view_routes.dart';
import 'package:icook_mobile/core/constants/view_state.dart';
import 'package:icook_mobile/models/response/Dish/getmydishes.dart';
import 'package:icook_mobile/ui/Onboarding_screens/Onboarding_screens.dart';
import 'package:icook_mobile/ui/details_screen/details_screen.dart';
import 'package:icook_mobile/ui/edit_profile_screen/edit_profile.dart';
import 'package:icook_mobile/ui/forgot_password_screen/forgot_password_screen.dart';
import 'package:icook_mobile/ui/home_page/home_page.dart';
import 'package:icook_mobile/ui/login_screen/login_screen.dart';
import 'package:icook_mobile/ui/other_users/other_users.dart';
import 'package:icook_mobile/ui/settings_screen/settings_screen.dart';
import 'package:icook_mobile/ui/signup_screen/signup_screen.dart';
import 'package:icook_mobile/ui/splash_screen/splash_screen.dart';

/// Class that generates routes for the application
///   - Routes are generated by the list of routes in the app
///   - Routes can also require parameters. e.g. `PostDetailView(post: post)`
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    return GetRouteBase(
      settings: RouteSettings(name: settings.name),
      page: _generateView(settings),
      fullscreenDialog: _fullScreenDialogs.contains(settings.name),
    );
  }

  static Widget _generateView(RouteSettings settings) {
    switch (settings.name) {
      //all veiws will be here
      case ViewRoutes.splash:
        return SplashScreen();

      case ViewRoutes.home:
        return HomePage();

      case ViewRoutes.edit_profile:
        return EditProfile();

      case ViewRoutes.onboarding:
        return OnboardingScreen();

      case ViewRoutes.recipe_details:
      final dish = settings.arguments as Dishe;
        return DetailsScreen(dish: dish);
      case ViewRoutes.userprofile:
        return OtherUserInfoScreen();

      case ViewRoutes.settings:
        return SettingsScreen();

      case ViewRoutes.login:
        return LoginScreen();

      case ViewRoutes.signup:
        return SignUpScreen();

      case ViewRoutes.forogotpassword:
        return ForgotPasswordScreen();

      default:
        return Scaffold(
          body: Center(
            child: Text('No route defined for ${settings.name}'),
          ),
        );
    }
  }

  // Add routes that should behave as fullScreenDialogs
  static final _fullScreenDialogs = [
    // Routes.route_1,
    // Routes.route_2,
  ];
}
